services:
  api-service:
    image: ghcr.io/anyone-protocol/api-service:latest
    restart: always
    env_file:
      - .env
    environment:
      GEODATADIR: "/usr/src/app/data/node_modules/geoip-lite/data"
      GEOTMPDIR: "/usr/src/app/data/node_modules/geoip-lite/tmp"
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - ./data/:/usr/src/app/data
  mongodb:
    image: mongo:8.0.12
    restart: always
    ports:
      - "${MONGODB_PORT:-27017}:27017"
    volumes:
      - ./data/mongodb:/data/db
