version: '2.2'
services:
  api-service:
    image: ghcr.io/anyone-protocol/api-service:latest
    restart: always
    env_file:
      - .env
    environment:
      GEODATADIR: "/usr/src/app/data/node_modules/geoip-lite/data"
      GEOTMPDIR: "/usr/src/app/data/node_modules/geoip-lite/tmp"
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - ./data/:/usr/src/app/data
